version: '3.8'

services:
  co2-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ./gradlew bootRun
    develop:
      watch:
        - path: ./src
          action: sync
