services:
  co2-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
