name: Frontend CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Start frontend
        run: npm run dev &

      - name: Wait for frontend
        run: |
          for i in {1..60}; do
            if curl -s http://localhost:5173 > /dev/null; then
              echo "Frontend is up"
              exit 0
            fi
            echo "Waiting for frontend..."
            sleep 2
          done
          echo "Frontend did not start in time"
          exit 1



      - name: Run Cypress tests
        run: npx cypress run

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u winksluizeman --password-stdin

      - name: Build frontend image
        run: docker build -t ghcr.io/winksluizeman/co2tracker-frontend:${{ github.sha }} .

      - name: Push frontend image
        run: docker push ghcr.io/winksluizeman/co2tracker-frontend:${{ github.sha }}
