name: Frontend CI/CD

on:
  push:
    branches: [ "master" ]


jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Start frontend
        run: npm run dev &

      - name: Wait for frontend
        run: |
          for i in {1..60}; do
            if curl -s http://localhost:5173 > /dev/null; then
              echo "Frontend is up"
              exit 0
            fi
            echo "Waiting for frontend..."
            sleep 2
          done
          echo "Frontend did not start in time"
          exit 1

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos


  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/winksluizeman/co2tracker-frontend:latest
            ghcr.io/winksluizeman/co2tracker-frontend:${{ github.sha }}
